CREATE TABLE IF NOT EXISTS NEWS(
ID INT PRIMARY KEY AUTO_INCREMENT,  TITLE VARCHAR(255),
    CONTENTS VARCHAR(255),
    NEWSDAY VARCHAR(255),
    IMAGE VARCHAR(255),
    COMPANY VARCHAR(255))



INSERT INTO NEWS (TITLE, CONTENTS, NEWSDAY, IMAGE, COMPANY)
    VALUES (%s, %s, %s, %s, %s)

